Add deployment to openshift

diff --git a/.github/workflows/github-actions-template.yml b/.github/workflows/github-actions-template.yml
--- a/.github/workflows/github-actions-template.yml
+++ b/.github/workflows/github-actions-template.yml
@@ -133,3 +133,52 @@ jobs:
         run: |
           docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ needs.extract-info.outputs.project_name }}:${{ needs.extract-info.outputs.version }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ needs.extract-info.outputs.project_name }}:latest
           docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ needs.extract-info.outputs.project_name }}:latest
+
+
+  deployment:
+    runs-on: ubuntu-latest
+    needs: [extract-info, build, create-github-release, build-and-push-docker-image]
+
+    env:
+      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
+      OPENSHIFT_USERNAME: ${{ secrets.OPENSHIFT_USERNAME }}
+      OPENSHIFT_PASSWORD: ${{ secrets.OPENSHIFT_PASSWORD }}
+      OPENSHIFT_NAMESPACE: ""
+      APP_NAME: "${{ needs.extract-info.outputs.project_name }}"
+      APP_PORT: ""
+
+    outputs:
+      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+
+    steps:
+        - name: Log in to OpenShift
+          uses: redhat-actions/oc-login@v1
+          with:
+            openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
+            openshift_username: ${{ env.OPENSHIFT_USER }}
+            openshift_password: ${{ env.OPENSHIFT_PASSWORD }}
+            insecure_skip_tls_verify: true
+            namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+
+        - name: Create and expose app
+          id: deploy-and-expose
+          uses: redhat-actions/oc-new-app@v1
+          with:
+            app_name: ${{ env.APP_NAME }}
+            image: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ needs.extract-info.outputs.project_name }}:latest
+            namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+            port: ${{ env.APP_PORT }}
+
+        - name: Print application URL
+          env:
+            ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+            SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+          run: |
+            [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+            echo
+            echo "======================== Your application is available at: ========================"
+            echo ${{ env.ROUTE }}
+            echo "==================================================================================="
+            echo
+            echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
