introduce blue-green deployment

diff --git a/.github/workflows/github-actions-template.yml b/.github/workflows/github-actions-template.yml
--- a/.github/workflows/github-actions-template.yml
+++ b/.github/workflows/github-actions-template.yml
@@ -34,12 +34,17 @@ jobs:
           # Remove -SNAPSHOT suffix if present
           release_version=${version%-SNAPSHOT}
           echo "Release version: $release_version"
+          # Replace dots with dashes in version
+          version_dashed=$(echo $release_version | tr '.' '-')
+          echo "Dashed version: $version_dashed"
           echo "::set-output name=project_name::$project_name"
           echo "::set-output name=version::$release_version"
+          echo "::set-output name=version_dashed::$version_dashed"
 
     outputs:
       project_name: ${{ steps.extract-info.outputs.project_name }}
       version: ${{ steps.extract-info.outputs.version }}
+      version_dashed: ${{ steps.extract-info.outputs.version_dashed }}
 
   build:
     runs-on: ubuntu-latest
@@ -163,6 +168,7 @@ jobs:
       OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
       APP_NAME: "${{ needs.extract-info.outputs.project_name }}"
       IMAGE_TAG: "${{ needs.extract-info.outputs.version }}"
+      IMAGE_TAG_DASHERIZED: ${{ needs.extract-info.outputs.version_dashed }}
       APP_PORT: ""
 
     outputs:
@@ -184,8 +190,30 @@ jobs:
 
         - name: Replace image tag in deployment file
           run: |
-            sed -i "s|{{IMAGE_TAG}}|${{ env.IMAGE_TAG }}|g" deployment.yaml
+            sed -i "s|{{IMAGE_TAG}}|${{ env.IMAGE_TAG }}|g" deployment-green-new.yaml
+            sed -i "s|{{IMAGE_TAG_DASHERIZED}}|${{ env.IMAGE_TAG_DASHERIZED }}|g" deployment-green-new.yaml
 
-        - name: Create Pod in OpenShift
+        - name: Deploy Blue Deployment
           run: |
-              oc apply -f deployment.yaml
+            oc apply -f deployment-green-new.yaml
+
+        - name: Wait for Blue Deployment to start up ... (20s)
+          run: sleep 20
+
+        - name: Update Route to Blue Deployment
+          run: |
+            oc patch route ${{ env.APP_NAME }}-route -p '{"spec":{"to":{"name":"${{ env.APP_NAME }}-${{ env.IMAGE_TAG_DASHERIZED }}-service"}}}'
+
+#        - name: Clean up Old Deployment
+#          run: |
+#            oc delete deployment ${{ env.APP_NAME }}-green || true
+#            oc delete service ${{ env.APP_NAME }}-green-service || true
+
+#        - name: Promote Blue to Green
+#          run: |
+#            oc patch deployment ${{ env.APP_NAME }}-blue -p '{"metadata": {"name": "${{ env.APP_NAME }}-green"}}'
+#            oc patch deployment ${{ env.APP_NAME }}-blue -p '{"spec": {"selector": {"matchLabels": {"app": "${{ env.APP_NAME }}"}}}}'
+#            oc patch deployment ${{ env.APP_NAME }}-blue -p '{"spec": {"template": {"metadata": {"labels": {"app": "${{ env.APP_NAME }}"}}}}}'
+#
+#            oc patch service ${{ env.APP_NAME }}-blue-service -p '{"spec": {"selector": {"app": "${{ env.APP_NAME }}-green"}}}'
+#            oc rename service ${{ env.APP_NAME }}-blue-service ${{ env.APP_NAME }}-green-service || true
